config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'upstream_user'

module ActionDispatch
  module Routing
    class Mapper
      def resources3(*args)
        resources(*args) do
          scope module: args[0] do
            yield
          end
        end
      end
    end
  end
end

Rails.application.routes.draw do
  resources :courses
  root to: 'assignments#index'
  resources :sessions, only: %i[create index]
  delete '/sessions', to: 'sessions#destroy'
  resources :tags
  resources :peer_review_question_answers
  resources :peer_review_questions
  resources :peer_reviews
  resources :assignments
  resources :users
  resources :exercise_types
  resources :exercises

  constraints(->(request) { UpstreamUser.new(request.session[:user_id]).get.administrator? }) do
    mount Sidekiq::Web => '/sidekiq'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v0, defaults: { format: :json } do
      resources3 :assignments, only: :show do
        resources :peer_review_exercise, only: :index
      end
      resources3 :exercises, only: :create do
        get 'template.zip', to: 'zips#template'
        get 'model_solution.zip', to: 'zips#model_solution'
        resources :results, only: :create
      end
      resources :peer_reviews, only: :create
      get 'users/current/progress', to: 'users#progress' # TODO: better route?
    end
  end
end

app/models/assignment.rb
# frozen_string_literal: true

class Assignment < ApplicationRecord
  belongs_to :exercise_type
  has_many :exercises
  belongs_to :course

  validates :description, presence: true
end

app/controllers/api/v0/assignments/peer_review_exercise_controller.rb
# frozen_string_literal: true

module Api
  module V0
    module Assignments
      class PeerReviewExerciseController < BaseController
        before_action :ensure_signed_in!, only: :index

        def index
          assignment = Assignment.find(params[:assignment_id])
          cnt = params[:count].to_i

          exercises = PeerReview.new.draw_exercises(assignment, current_user, cnt)

          raise NoExerciseError if exercises.empty? || exercises.first.nil?

          pr_questions = exercises.first.assignment.exercise_type.peer_review_questions
          render json: { exercises: exercises, peer_review_questions: pr_questions,
                         tags: Tag.recommended, testing_type: testing_type(assignment.exercise_type) }
        end

        def testing_type(exercise_type)
          if exercise_type.testing_type == 'input_output'
            'input_output'
          elsif exercise_type.testing_type == 'student_written_tests' || exercise_type.testing_type == 'whole_test_code_for_set_up_code'
            'unit_tests'
          elsif exercise_type.testing_type == 'io_and_code' || exercise_type.testing_type == 'tests_for_set_up_code'
            'io_and_code'
          end
        end
      end
    end
  end
end

app/controllers/api/v0/assignments_controller.rb
# frozen_string_literal: true

module Api
  module V0
    class AssignmentsController < BaseController
      # GET /assignments/1
      def show
        @assignment = Assignment.find(params[:id])
        @exercise_type = @assignment.exercise_type

        render json: { assignment: @assignment, tags: Tag.recommended, template: @exercise_type.code_template,
                       mandatory_tags: @assignment.mandatory_tags, language: @assignment.course.language,
                       input_type: @exercise_type.input_type, output_type: @exercise_type.output_type, testing_a_method: @exercise_type.testing_a_method }
          .merge(testing_type(@exercise_type))
      end

      def testing_type(exercise_type)
        if exercise_type.testing_type == 'input_output' || exercise_type.testing_type == 'input_output_tests_for_set_up_code'
          { exercise_type: exercise_type.testing_type }
        elsif exercise_type.testing_type == 'student_written_tests' || exercise_type.testing_type == 'whole_test_code_for_set_up_code'
          { test_template: @exercise_type.test_template, exercise_type: if exercise_type.testing_type == 'student_written_tests'
                                                                          'unit_tests'
                                                                        else
                                                                          'whole_test_code_for_set_up_code'
                                                                       end }
        elsif exercise_type.testing_type == 'io_and_code' || exercise_type.testing_type == 'tests_for_set_up_code'
          { test_template: @exercise_type.test_method_template, exercise_type: exercise_type.testing_type }
        end
      end
    end
  end
end

app/controllers/assignments_controller.rb
# frozen_string_literal: true

class AssignmentsController < ApplicationController
  before_action :set_assignment, only: %i[show edit update destroy]

  # GET /assignments
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1
  def show
    @exercises = Exercise.page(params[:page]).per(25).where(assignment_id: params[:id])
    @exercises_count = Exercise.where(assignment_id: params[:id]).count
    @finished_count = Exercise.where(assignment_id: params[:id], status: 'finished').count
    @error_count = Exercise.where(assignment_id: params[:id], status: 'error').count
    @timeout_count = Exercise.where(assignment_id: params[:id], status: 'sandbox_timeout').count
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit; end

  # POST /assignments
  def create
    @assignment = Assignment.new(assignment_params)

    if @assignment.save
      redirect_to @assignment, notice: 'Assignment was successfully created.'
    else
      render :new, notice: 'Assignment creation failed.'
    end
  end

  # PATCH/PUT /assignments/1
  def update
    if @assignment.update(assignment_params)
      redirect_to @assignment, notice: 'Assignment was successfully updated.'
    else
      render :edit, notice: 'Assignment update failed.'
    end
  end

  # DELETE /assignments/1
  def destroy
    @assignment.destroy
    redirect_to assignments_url, notice: 'Assignment was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_assignment
    @assignment = Assignment.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def assignment_params
    params.require(:assignment).permit(:description, :exercise_type_id, :course_id, :part, :show_results_to_user, :mandatory_tags, :peer_review_count, :pr_part)
  end
end

app/helpers/assignments_helper.rb
# frozen_string_literal: true

module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<%= form_with(model: assignment, local: true) do |form| %>
  <% if assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>For instructions, see <a href="https://github.com/rage/crowdsorceress/blob/english/documentation/admin_instructions.md">the documentation</a></p>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :assignment_description, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :exercise_type_id %>
    <%= form.collection_select :exercise_type_id, ExerciseType.all, :id, :name, { prompt: true }, class: "form-control" %>
  </div>

    <div class="field">
      <%= form.label :course_id %>
      <%= form.collection_select :course_id, Course.all, :id, :name, { prompt: true }, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label :part %>
      <%= form.text_field :part, id: :assignment_part, class: "form-control" %>
    </div>

  <div class="actions">
    <%= form.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<h1>Editing Assignment</h1>

<%= render 'form', assignment: @assignment %>

<%= link_to 'Show', @assignment, class: "btn btn-primary" %>
<%= link_to 'Back', assignments_path, class: "btn btn-secondary" %>

app/views/assignments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assignments</h1>

<table class="table table-hover ">
  <thead class="thead-inverse">
    <tr>
      <th>Id</th>
      <th>Description</th>
      <th>Exercise type</th>
      <th>Exercises</th>
    </tr>
  </thead>

  <tbody>
    <% @assignments.each do |assignment| %>
      <tr>
        <td><%= link_to assignment.id, assignment %></td>
        <td><%= link_to assignment.description, assignment %></td>
        <td><%= link_to assignment.exercise_type.name, assignment.exercise_type %></td>
        <td><%= link_to assignment.exercises.count, exercises_path(assignment_search_term: assignment.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assignment', new_assignment_path, class: "btn btn-primary" %>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>

<%= render 'form', assignment: @assignment %>

<%= link_to 'Back', assignments_path, class: "btn btn-secondary" %>

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Assignment <%= @assignment.id %></h1>

<p>
  <strong>Description:</strong>
  <%= @assignment.description %>
</p>

<p>
  <strong>Exercise type:</strong>
  <%= link_to @assignment.exercise_type.name, @assignment.exercise_type %>
</p>

<% if @assignment.course %>
  <p>
    <strong>Course:</strong>
    <%= link_to @assignment.course.name, @assignment.course %>
  </p>

  <p>
    <strong>Part:</strong>
    <%= @assignment.part %>
  </p>
<% end %>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Embed:</h5>
    <strong>HTML:</strong>
    <pre><code><%= "<div class='crowdsorcerer-widget' data-assignment='#{@assignment.id}'></div>" %></code></pre>
    <strong>University of Helsinki materials:</strong>
    <pre><code><%= "<crowdsorcerer id='#{@assignment.id}'></crowdsorcerer>" %></code></pre>
  </div>
</div>
<br>

<br>

<% if @exercises_count > 0 %>

<h2>Exercises for assignment <%= @assignment.id%></h2>

<p>
  <strong><%= @exercises_count %> exercises in total</strong>
    <ul>
        <li><%= "finished: #{@finished_count} (#{@finished_count/@exercises_count.to_f * 100}%)"%></li>
        <li><%= "errror: #{@error_count} (#{@error_count/@exercises_count.to_f * 100}%)" %></li>
        <li><%= "timeout: #{@timeout_count} (#{@timeout_count/@exercises_count.to_f * 100}%)" %></li>
    </ul>
</p>

  <table class="table table-hover">
    <thead class="thead-inverse">
      <tr>
        <th>User</th>
        <th>Assignment</th>
        <th>Status</th>
        <th>Peer reviews count</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @exercises.each do |exercise| %>
        <tr>
          <td><%= link_to exercise.user.username, exercise.user %></td>
          <td><%= link_to exercise.assignment_id, exercise.assignment %></td>
          <td><%= exercise.status %></td>
          <td><%= exercise.peer_reviews_count %></td>
          <td><%= link_to 'Show', exercise %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

<%= paginate @exercises %>
<%= page_entries_info @exercises %>

<br>

<%= link_to 'Edit', edit_assignment_path(@assignment), class: "btn btn-primary"%>
<%= link_to 'Back', assignments_path, class: "btn btn-secondary" %>
<%= link_to 'Destroy', @assignment, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }  %>