config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'upstream_user'

module ActionDispatch
  module Routing
    class Mapper
      def resources3(*args)
        resources(*args) do
          scope module: args[0] do
            yield
          end
        end
      end
    end
  end
end

Rails.application.routes.draw do
  resources :courses
  root to: 'assignments#index'
  resources :sessions, only: %i[create index]
  delete '/sessions', to: 'sessions#destroy'
  resources :tags
  resources :peer_review_question_answers
  resources :peer_review_questions
  resources :peer_reviews
  resources :assignments
  resources :users
  resources :exercise_types
  resources :exercises

  constraints(->(request) { UpstreamUser.new(request.session[:user_id]).get.administrator? }) do
    mount Sidekiq::Web => '/sidekiq'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v0, defaults: { format: :json } do
      resources3 :assignments, only: :show do
        resources :peer_review_exercise, only: :index
      end
      resources3 :exercises, only: :create do
        get 'template.zip', to: 'zips#template'
        get 'model_solution.zip', to: 'zips#model_solution'
        resources :results, only: :create
      end
      resources :peer_reviews, only: :create
      get 'users/current/progress', to: 'users#progress' # TODO: better route?
    end
  end
end

app/controllers/api/v0/peer_reviews_controller.rb
# frozen_string_literal: true

module Api
  module V0
    class PeerReviewsController < BaseController
      # POST /peer_reviews
      before_action :set_exercise, only: %i[create]

      def create
        @peer_review = current_user.peer_reviews.find_or_initialize_by(exercise: @exercise, comment: params[:peer_review][:comment])

        add_tags

        PeerReview.transaction do
          if @peer_review.save
            render json: @peer_review, status: :created, location: @peer_review
            create_question_answers
          else
            render json: @peer_review.errors, status: :unprocessable_entity
          end
        end
      end

      private

      def add_tags
        params[:exercise][:tags].each do |tag|
          tag = Tag.find_or_initialize_by(name: tag.strip.delete("\n").gsub(/\s+/, ' ').downcase)
          @peer_review.tags << tag unless @peer_review.tags.include?(tag)
        end
      end

      def set_exercise
        @exercise = Exercise.find(params[:exercise][:exercise_id])
      end

      def create_question_answers
        reviews = params[:peer_review][:answers]
        questions = @exercise.assignment.exercise_type.peer_review_questions
        @peer_review.peer_review_question_answers = [] # reset previous answers

        questions.each do |q|
          @peer_review.peer_review_question_answers.create!(peer_review_question: q, grade: reviews[q.question])
        end
      end
    end
  end
end

app/controllers/peer_reviews_controller.rb
# frozen_string_literal: true

class PeerReviewsController < ApplicationController
  before_action :set_peer_review, only: %i[show edit update destroy]
  before_action :set_exercise, only: %i[create]

  # GET /peer_reviews
  def index
    @peer_reviews = PeerReview.page(params[:page])
    @peer_reviews_count = PeerReview.all.count
  end

  # GET /peer_reviews/1
  def show; end

  # GET /peer_reviews/new
  def new
    @peer_review = PeerReview.new
  end

  # GET /peer_reviews/1/edit
  def edit; end

  # POST /peer_reviews
  def create
    @peer_review = PeerReview.new(peer_review_params)

    if @peer_review.save
      redirect_to @peer_review, notice: 'Peer review successfully created.'
    else
      render :new, notice: 'Peer review creation failed.'
    end
  end

  # PATCH/PUT /peer_reviews/1
  def update
    if @peer_review.update(peer_review_params)
      redirect_to @peer_review, notice: 'Peer review successfully updated.'
    else
      render :edit, notice: 'Peer review update failed.'
    end
  end

  # DELETE /peer_reviews/1
  def destroy
    @peer_review.destroy
    redirect_to peer_reviews_url, notice: 'Peer review was successfully destroyed.'
  end

  private

  def set_exercise
    @exercise = Exercise.find(params[:exercise][:exercise_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_peer_review
    @peer_review = PeerReview.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def peer_review_params
    params.require(:peer_review).permit(:comment, :answers)
    params.require(:exercise).permit(:exercise_id, :tags)
  end
end

app/helpers/peer_reviews_helper.rb
# frozen_string_literal: true

module PeerReviewsHelper
end

app/views/peer_reviews/_form.html.erb
<%= form_with(model: peer_review, local: true) do |form| %>
  <% if peer_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(peer_review.errors.count, "error") %> prohibited this peer_review from being saved:</h2>

      <ul>
      <% peer_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :peer_review_user_id, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :exercise_id %>
    <%= form.collection_select :exercise_id, Exercise.all, :id, :id, { prompt: true }, class: "form-control" %>
    </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, id: :peer_review_comment, class: "form-control" %>
  </div>

  <div class="actions">
  <%= form.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/peer_reviews/edit.html.erb
<h1>Editing Peer Review</h1>

<%= render 'form', peer_review: @peer_review %>

<%= link_to 'Show', @peer_review %> |
<%= link_to 'Back', peer_reviews_path %>

app/views/peer_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Peer Reviews</h1>

<p>Peer reviews are not supported in the English/Python version</p>

<p>
  <strong>There are <%= @peer_reviews_count %> peer reviews</strong>
</p>

<table class="table table-hover">
  <thead class="thead-inverse" >
    <tr>
      <th>Reviewer</th>
      <th>Exercise</th>
      <th>Assignment</th>
      <th>Reviewee</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @peer_reviews.each do |peer_review| %>
      <tr>
        <td><%= link_to peer_review.user.username, peer_review.user %></td>
        <td><%= link_to peer_review.exercise_id, peer_review.exercise %></td>
        <td><%= link_to peer_review.exercise.assignment.id, peer_review.exercise.assignment %></td>
        <td><%= link_to peer_review.exercise.user.username, peer_review.exercise.user %></td>
        <td><%= link_to 'Show', peer_review %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @peer_reviews %>
<%= page_entries_info @peer_reviews %>


<br>

<%= link_to 'New Peer Review', new_peer_review_path, class: "btn btn-primary"%>

app/views/peer_reviews/new.html.erb
<h1>New Peer Review</h1>

<%= render 'form', peer_review: @peer_review %>

<%= link_to 'Back', peer_reviews_path, class: "btn btn-secondary" %>

app/views/peer_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Peer Review <%= @peer_review.id %></h1>
<p>
<strong>Created:</strong>
  <%= @peer_review.created_at %>
</p>


<p>
<strong>Updated:</strong>
  <%= @peer_review.updated_at %>
</p>

<p>
  <strong>Reviewer:</strong>
  <%= link_to @peer_review.user.username, @peer_review.user %>
</p>

<p>
  <strong>Exercise:</strong>
  <%= link_to @peer_review.exercise_id, @peer_review.exercise %>
</p>

<p>
  <strong>Assignment:</strong>
  <%= link_to @peer_review.exercise.assignment.id, @peer_review.exercise.assignment %>
</p>

<p>
  <strong>Reviewee:</strong>
  <%= link_to @peer_review.exercise.user.username, @peer_review.exercise.user %>
</p>

<p>
  <strong>Grades:</strong>
  <ul>
    <% @peer_review.peer_review_question_answers.each do |answer|%>
        <li>
          <%= answer.peer_review_question.question %>: <%= answer.grade %>
        </li>
    <% end %>
  </ul>
  </p>
<p>
  <strong>Average grade: </strong>
  <%= @peer_review.average_grade %>
</p>

<p>
  <strong>Comment:</strong>
  <pre>
  <%= @peer_review.comment %>
  </pre>
</p>

<p>
<strong>Grades:</strong>
  <ul>
    <% @peer_review.peer_review_question_answers.each do |answer|%>
      <li>
        <%= answer.peer_review_question.question %>: <%= answer.grade %>
      </li>
    <% end %>
  </ul>
  <p>
    <strong>Average grade: </strong>
    <%= @peer_review.average_grade %>
  </p>
</p>

<p>
  <strong>Tags:</strong>
    <ul>
    <% @peer_review.tags.each do |tag|%>
      <li>
        <%= link_to tag.name, tag %>
      </li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_peer_review_path(@peer_review), class: "btn btn-primary" %>
<%= link_to 'Back', peer_reviews_path, class: "btn btn-secondary" %>
<%= link_to 'Destroy', peer_review_path, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }%>