config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'upstream_user'

module ActionDispatch
  module Routing
    class Mapper
      def resources3(*args)
        resources(*args) do
          scope module: args[0] do
            yield
          end
        end
      end
    end
  end
end

Rails.application.routes.draw do
  resources :courses
  root to: 'assignments#index'
  resources :sessions, only: %i[create index]
  delete '/sessions', to: 'sessions#destroy'
  resources :tags
  resources :peer_review_question_answers
  resources :peer_review_questions
  resources :peer_reviews
  resources :assignments
  resources :users
  resources :exercise_types
  resources :exercises

  constraints(->(request) { UpstreamUser.new(request.session[:user_id]).get.administrator? }) do
    mount Sidekiq::Web => '/sidekiq'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v0, defaults: { format: :json } do
      resources3 :assignments, only: :show do
        resources :peer_review_exercise, only: :index
      end
      resources3 :exercises, only: :create do
        get 'template.zip', to: 'zips#template'
        get 'model_solution.zip', to: 'zips#model_solution'
        resources :results, only: :create
      end
      resources :peer_reviews, only: :create
      get 'users/current/progress', to: 'users#progress' # TODO: better route?
    end
  end
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :exercises_tags, dependent: :destroy
  has_many :peer_reviews_tags, dependent: :destroy
  has_many :exercises, through: :exercises_tags
  has_many :peer_reviews, through: :peer_reviews_tags

  scope :recommended, -> { where(recommended: true) }

  validates :name, uniqueness: true

  def exercises_via_peer_reviews
    PeerReviewsTag.where(tag: self).map { |prt| prt.peer_review.exercise }.uniq
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  before_action :set_tag, only: %i[show edit update destroy]

  # GET /tags
  def index
    @tags = Tag.page(params[:page])
    @tags_count = Tag.all.count
  end

  # GET /tags/1
  def show
    @exercises = @tag.exercises
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit; end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to @tag, notice: 'Tag was successfully created.'
    else
      render :new, notice: 'Tag creation failed.'
    end
  end

  # PATCH/PUT /tags/1
  def update
    if @tag.update(tag_params)
      redirect_to @tag, notice: 'Tag was successfully updated.'
    else
      render :edit, notice: 'Tag update failed.'
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    redirect_to tags_url, notice: 'Tag was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def tag_params
    params.require(:tag).permit(:name, :recommended)
  end
end

app/helpers/tags_helper.rb
# frozen_string_literal: true

module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :tag_name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :recommended %>
    <%= form.check_box :recommended, id: :tag_recommended, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>
<%= link_to 'Back', tags_path, class: "btn btn-secondary" %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<p>Tags are not supported in the English/Python version</p>

<strong>There are <%= @tags_count%> tags</strong>

<table class="table table-hover ">
  <thead class="thead-inverse" >
    <tr>
      <th>Name</th>
      <th class="recommended-column">Recommended</th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= link_to tag.name, tag %></td>
        <td class="recommended-column"><%= tag.recommended ? "\u2713": "" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @tags %>
<%= page_entries_info @tags %>

<br>

<%= link_to 'New Tag', new_tag_path, class: "btn btn-primary" %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @tag.name %></h1>

<p>
  <strong>Recommended:</strong>
  <%= @tag.recommended %>
</p>

<% if @tag.exercises.empty? && @tag.exercises_via_peer_reviews.empty? %>
  <p>No exercises tagged with <%= @tag.name %></p>
<% else %>
  <strong>Exercises tagged with <%= @tag.name %>:</strong>
    <ul>
    <% @tag.exercises.each do |exercise| %>
    <li>
      <%= link_to exercise.id, exercise %>
    </li>
    <% end %>
    <% @tag.exercises_via_peer_reviews.each do |exercise|%>
    <li>
      <%= link_to exercise.id, exercise %>
    </li>
    <% end %>
  </ul>
<% end %>

<p>
<%= link_to 'Edit', edit_tag_path(@tag), class: "btn btn-primary" %>
<%= link_to 'Back', tags_path, class: "btn btn-secondary" %>
<%= link_to 'Destroy', tag_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
</p>