config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'upstream_user'

module ActionDispatch
  module Routing
    class Mapper
      def resources3(*args)
        resources(*args) do
          scope module: args[0] do
            yield
          end
        end
      end
    end
  end
end

Rails.application.routes.draw do
  resources :courses
  root to: 'assignments#index'
  resources :sessions, only: %i[create index]
  delete '/sessions', to: 'sessions#destroy'
  resources :tags
  resources :peer_review_question_answers
  resources :peer_review_questions
  resources :peer_reviews
  resources :assignments
  resources :users
  resources :exercise_types
  resources :exercises

  constraints(->(request) { UpstreamUser.new(request.session[:user_id]).get.administrator? }) do
    mount Sidekiq::Web => '/sidekiq'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v0, defaults: { format: :json } do
      resources3 :assignments, only: :show do
        resources :peer_review_exercise, only: :index
      end
      resources3 :exercises, only: :create do
        get 'template.zip', to: 'zips#template'
        get 'model_solution.zip', to: 'zips#model_solution'
        resources :results, only: :create
      end
      resources :peer_reviews, only: :create
      get 'users/current/progress', to: 'users#progress' # TODO: better route?
    end
  end
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="/">Crowdsorceress</a>
    <% if admin? %>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= navigation_link 'Assignments', assignments_path %>
      </li>
      <li class="nav-item">
        <%= navigation_link 'Courses', courses_path %>
      </li>
      <li class="nav-item">
        <%= navigation_link 'Exercise Types', exercise_types_path %>
      </li>
      <li class="nav-item">
        <%= navigation_link 'Exercises', exercises_path %>
      </li>
      <li class="nav-item">
        <%= navigation_link 'Tags', tags_path %>
      </li>
      <li class="nav-item">
        <%= navigation_link 'Peer Reviews', peer_reviews_path %>
      </li>
      <li class="nav-item">
        <%= navigation_link 'Peer Review Questions', peer_review_questions_path %>
      </li>
      <li class="nav-item">
      <%= navigation_link 'Users', users_path %>
    </li>
  </ul>
    <% if current_user %>
      <%= link_to 'Log out', sessions_path, method: :delete, data: { confirm: 'Do you want to log out?' }, class: "float-right btn btn-danger nomargin" %>
    <% end %>
  <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdsorceress</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.js" integrity="sha256-jVfFb7AbGi7S/SLNl8SB4/MYaf549eEs+NlIWMoARHg=" crossorigin="anonymous"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render partial: 'layouts/navigation' %>
<div class="container">
  <%= yield %>
</div>
</body>
</html>